env:
  node: true
  commonjs: true
  es6: true
extends:
  - google
parser: babel-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  "max-len": [2, 120, 4, {"ignoreUrls": true}]

